language: generic
sudo: true

os:
#  - linux
  - osx

addons:
  apt:
    packages:
    - sbcl
    - git
    - build-essential
    - autoconf
    - automake
    - autogen
    - autopoint
    - libncurses5-dev
    - libx11-dev
    - libxpm-dev
    - libgtk2.0-dev
    - zlib1g-dev
    - libpcre3-dev
    - libcurl4-gnutls-dev
    - libssl-dev
    - libtool
    - texinfo

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install sbcl gettext; fi

script:
  - cd build/
  - ./build.sh