language: generic

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx # OS X 10.13
      osx_image: xcode9.3beta
    - os: osx # OS X 10.12
      osx_image: xcode9.2
    - os: osx # OS X 10.11
      osx_image: xcode8

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: 'ppa:keithw/glfw3'
    packages:
      - sbcl
      - time
      - autoconf
      - automake
      - autogen
      - autopoint
      - libncurses-dev
      - libx11-dev
      - libxpm-dev
      - libgtk2.0-dev
      - zlib1g-dev
      - libpcre3-dev
      - libcurl4-gnutls-dev
      - libssl-dev
      - libgcrypt-dev
      - libglfw3-dev
      - libtool
      - liblzma-dev
      - texinfo
      - xsel

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  # Install deps in a needlessly convoluted manner because brew sucks balls
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list autoconf &>/dev/null && brew upgrade autoconf || brew install autoconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list automake &>/dev/null && brew upgrade automake || brew install automake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list automake &>/dev/null && brew upgrade automake || brew install automake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list gettext &>/dev/null && brew upgrade gettext || brew install gettext; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list glfw &>/dev/null && brew upgrade glfw || brew install glfw; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list gnu-sed &>/dev/null && brew upgrade gnu-sed || brew install gnu-sed; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list gnutls &>/dev/null && brew upgrade gnutls || brew install gnutls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list libgcrypt &>/dev/null && brew upgrade libgcrypt || brew install libgcrypt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list libtool &>/dev/null && brew upgrade libtool || brew install libtool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list openssl &>/dev/null && brew upgrade openssl || brew install openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list pcre &>/dev/null && brew upgrade pcre || brew install pcre; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list pkg-config &>/dev/null && brew upgrade pkg-config || brew install pkg-config; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list sbcl &>/dev/null && brew upgrade sbcl || brew install sbcl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list xz &>/dev/null && brew upgrade xz || brew install xz; fi
  # OS X gettext sucks
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link gettext --force; fi

script:
  - cd build
  - ./sbcl.sh download
  - cd sbcl
  - git apply ../src/sbcl-disable-frlock-test.diff
  - cd ..
  - ./build.sh
