language: generic

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - sbcl
      - autoconf
      - automake
      - autogen
      - autopoint
      - libncurses-dev
      - libx11-dev
      - libxpm-dev
      - libgtk2.0-dev
      - zlib1g-dev
      - libpcre3-dev
      - libcurl4-gnutls-dev
      - libssl-dev
      - libtool
      - texinfo
      - time

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf automake sbcl gettext pcre openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS" LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi

script:
  - cd build
  - ./build.sh
